### ISSUE TITLE
unknown service csi.v0.Identity when starting csi-driver-registrar

### ISSUE THREAD

**Issue by gosuri** [packethost/csi-packet#45]
Hi there! i'm looking for some guidance on this error: The csi-driver-registrar fails to start because it cannot find `csi.v0.Identity`. 

**Logs:**

```sh
$ kubectl logs csi-node-5w9vw csi-driver-registrar -n kube-system                                                                                                                                                                    
I1006 22:05:35.129613       1 main.go:75] Attempting to open a gRPC connection with: %!q(*string=0xc4202f8100)
I1006 22:05:35.129651       1 connection.go:68] Connecting to /csi/csi.sock
I1006 22:05:35.129831       1 connection.go:95] Still trying, connection is CONNECTING
I1006 22:05:35.130038       1 connection.go:92] Connected
I1006 22:05:35.130047       1 main.go:83] Calling CSI driver to discover driver name.
I1006 22:05:35.130057       1 connection.go:136] GRPC call: /csi.v0.Identity/GetPluginInfo
I1006 22:05:35.130062       1 connection.go:137] GRPC request:
I1006 22:05:35.130286       1 connection.go:139] GRPC response:
I1006 22:05:35.130330       1 connection.go:140] GRPC error: rpc error: code = Unimplemented desc = unknown service csi.v0.Identity
E1006 22:05:35.130347       1 main.go:88] rpc error: code = Unimplemented desc = unknown service csi.v0.Identity
```

**Node info:**
```yaml
  nodeInfo:
    architecture: amd64
    bootID: 14932bb1-5464-4298-894f-5dd77098e9a2
    containerRuntimeVersion: containerd://1.2.7-k3s1
    kernelVersion: 5.0.0-20-generic
    kubeProxyVersion: v1.14.6-k3s.1
    kubeletVersion: v1.14.6-k3s.1
    machineID: 6004594e4af342dea0470b5f6ed37cb6
    operatingSystem: linux
    osImage: Ubuntu 19.04
    systemUUID: 00000000-0000-0000-0000-0cc47a805582
```

**Snapshot of the images:**

```yaml 
images:
  - names:
    - docker.io/grafana/grafana@sha256:f398faf159712dbfddada80679f1411b1baa6fca3ee08317d785c41a2972124a
    - docker.io/grafana/grafana:6.3.5
    sizeBytes: 98592267
  - names:
    - docker.io/packethost/csi-packet@sha256:2532aa85e326e7f889d62fce9cf4ba186a29e1681edc2a464d8c22801e0ca09f
    - docker.io/packethost/csi-packet:196a346
    sizeBytes: 76774375
  - names:
    - docker.io/prom/prometheus@sha256:8f34c18cf2ccaf21e361afd18e92da2602d0fa23a8917f759f906219242d8572
    - docker.io/prom/prometheus:v2.11.1
    sizeBytes: 51075391
  - names:
    - gcr.io/kubernetes-helm/tiller@sha256:be79aff05025bd736f027eaf4a1b2716ac1e09b88e0e9493c962642519f19d9c
    - gcr.io/kubernetes-helm/tiller:v2.14.2
    sizeBytes: 30875059
  - names:
    - docker.io/rancher/klipper-helm@sha256:72690de1ae2259a41075e87ff453936a74e0f2dbf2ad1dd96a4f72136a48038d
    - docker.io/rancher/klipper-helm:v0.1.5
    sizeBytes: 27089525
  - names:
    - docker.io/prom/alertmanager@sha256:3d52ab7ef3a2e23e26a73cfd0ce13189e3796fb276b9af3e79664e4f743d8a1d
    - docker.io/prom/alertmanager:v0.18.0
    sizeBytes: 25080314
  - names:
    - docker.io/library/traefik@sha256:02cfdb77b0cd82d973dffb3dafe498283f82399bd75b335797d7f0fe3ebeccb8
    - docker.io/library/traefik:1.7.12
    sizeBytes: 20394307
  - names:
    - quay.io/k8scsi/csi-provisioner:v1.0.1
    sizeBytes: 18145019
  - names:
    - quay.io/k8scsi/csi-attacher:v1.0.1
    sizeBytes: 12672143
  - names:
    - docker.io/coredns/coredns@sha256:e030773c7fee285435ed7fc7623532ee54c4c1c4911fb24d95cd0170a8a768bc
    - docker.io/coredns/coredns:1.3.0
    sizeBytes: 12286817
  - names:
    - quay.io/coreos/kube-state-metrics:v1.6.0
    sizeBytes: 12176142
  - names:
    - quay.io/k8scsi/csi-node-driver-registrar:v1.0.1
    sizeBytes: 12038929
  - names:
    - quay.io/k8scsi/driver-registrar:v0.2.0
    sizeBytes: 11227293
  - names:
    - docker.io/prom/node-exporter@sha256:b2dd31b0d23fda63588674e40fd8d05010d07c5d4ac37163fc596ba9065ce38d
    - docker.io/prom/node-exporter:v0.18.0
    sizeBytes: 11100284
  - names:
    - docker.io/jimmidyson/configmap-reload@sha256:befec9f23d2a9da86a298d448cc9140f56a457362a7d9eecddba192db1ab489e
    - docker.io/jimmidyson/configmap-reload:v0.2.2
    sizeBytes: 9880745
  - names:
    - docker.io/prom/pushgateway@sha256:aeb2b7fe9f1464455dfea93494d8e84438bf5d60888fcc9e3554366191c1aba8
    - docker.io/prom/pushgateway:v0.8.0
    sizeBytes: 7863620
  - names:
    - docker.io/rancher/klipper-lb@sha256:2cff68f14dd050a5ab16b59a55d5ba34d6edc3f6edfc1ec5bd4e437d4ba47290
    - docker.io/rancher/klipper-lb:v0.1.1
    sizeBytes: 2708144
  - names:
    - k8s.gcr.io/pause@sha256:f78411e19d84a252e53bff71a4407a5686c46983a2c2eeed83929b888179acea
    - k8s.gcr.io/pause:3.1
    sizeBytes: 317164
```
