### ISSUE TITLE
PersistentVolume sample deployment missing from the Demos

### ISSUE THREAD

**Issue by enkelprifti98** [packethost/csi-packet#64]
It would be great to have a sample PV.yaml demo for users that would like to use persistent volumes, though not recommended for production use cases as PVCs handle the creation of PVs automatically.

I was able to deploy a  PV by manually creating a block storage volume on the Packet portal and then deploying this PV object:

```
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv1
  annotations:
    # fake it by indicating this is provisioned dynamically, so the system
    # works properly
    pv.kubernetes.io/provisioned-by: net.packet.csi
spec:
  storageClassName: csi-packet-performance
  # by default, the volume will be not deleted if you delete the PVC, change to
  # "Delete" if you wish the volume to be deleted automatically with the PVC
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: net.packet.csi
    fsType: ext4
    # You will have to add your Packet block storage volume ID for the volumeHandle
    volumeHandle: <block-volume-ID>
    volumeAttributes:
      storage.kubernetes.io/csiProvisionerIdentity: 1572974631219-8081-net.packet.csi
```
